version: '3.9'
services:
  db:
    image: postgres:13
    restart: unless-stopped
    container_name: palstala-db
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev
  tests:
    image: mcr.microsoft.com/playwright:focal
    working_dir: /var/app
    command: npm run test:migrate,pw
    volumes:
    - ./:/var/app
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/tests
      BUILD_DIR: .next-docker
