version: '3.9'
services:
  db:
    image: postgres:13
    restart: unless-stopped
    container_name: palstala-db
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev
